## gen-python schema.yaml > model.py
## gen-plantuml schema.yaml > schema.puml
## uv run gen_neo4j_constraints.py schema.yaml > constraints.cypher

id: https://example.org/knownet # change this later to id: https://github.com/myusername/my-project/course-profile
name: KnownetApplicationProfile
prefixes:
  ocds: http://data.tbfy.eu/ontology/ocds#
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  org: http://www.w3.org/ns/org# 
  dcterms: http://purl.org/dc/terms/
  xsd: http://www.w3.org/2001/XMLSchema# 
  ext: http://example.org/extensions/
  data: http://example.org/data/
  skos: http://www.w3.org/2004/02/skos/core#
  foaf: http://xmlns.com/foaf/0.1/ 

default_prefix: data

imports:
  - linkml:types

classes:
  # --- CLASS 1: CONTRACT ---
  Contract:
    class_uri: ocds:Contract
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:
        identifier: true
        slot_uri: ocds:contractId
        required: true
        range: string

      signing_date:
        slot_uri: ocds:dateContractSigned
        required: true
        range: datetime

      initial_value:
        slot_uri: ext:initialContractValue
        description: The initial value of the contract, available at Portal BASE. Has to be a positive float.
        required: true
        range: float

      final_value:
        slot_uri: ext:finalContractValue
        description: The final value of the contract, available at Portal BASE. Has to be a positive float.
        required: true
        range: float

      execution_deadline:
        slot_uri: ext:durationInDays
        description: The execution deadline of the contract in days, available at Portal BASE. Has to be a positive integer.
        required: true
        range: integer

      contract_type:
        slot_uri: ext:contractType
        description: The type of the contract, available at Portal BASE. Has to be one of the values defined in ContractTypeEnum.
        required: true
        multivalued: true
        range: ContractTypeEnum

      causes_deadline_change:
        slot_uri: ext:causesDeadlineChange
        description: The causes of the deadline change, available at Portal BASE 
        range: string

      causes_price_change:
        slot_uri: ext:causesPriceChange
        description: The causes of the price change, available at Portal BASE 
        range: string

    # 2. Slots (Object Properties / Links to other classes)
    slots:
      - EXECUTED_AT_LOCATION
      - HAS_CPV_CLASSIFICATION
      - HAS_DOCUMENT
    

  # --- CLASS 2: TENDER ---
  Tender:
    class_uri: ocds:Tender
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:
        identifier: true
        slot_uri: ocds:tenderId
        required: true
        range: string

      numberOfTenderers:
        slot_uri: ocds:numberOfTenderers
        range: integer

      procurement_method:
        slot_uri: ocds:procurementMethod
        required: true
        range: procurementMethodEnum

      procedure_type:
        slot_uri: ext:procedureType
        required: true
        description: The name of the type of the procedure used in Portugal, available at Portal BASE. Has to be one of the values defined in ProcedureTypeEnum. Each can be assigned to one of the 4 procurement methods defined in ProcurementMethodEnum.
        range: string

      publication_date:
        slot_uri: ext:dateTenderPublished
        description: The date when the tender was published, available at Portal BASE.
        range: datetime

      close_date:
        slot_uri: ext:dateTenderClosed
        description: The date when the tender was closed, available at Portal BASE.
        range: datetime

      environmental_criteria:
        slot_uri: ext:environmentalCriteria
        description: Flags if the tender had any environmental criteria considered in the award of contract, available at Portal BASE.
        range: boolean

      material_criteria:
        slot_uri: ext:materialCriteria
        description: Flags if the tender had any material criteria considered in the award of contract, available at Portal BASE.
        range: boolean

      centralized_procedure:
        slot_uri: ext:centralizedProcedure
        description: Flags if the tender was a centralized procedure, available at Portal BASE.
        range: boolean

    # 2. Slots (Object Properties / Links to other classes)
    slots:
      - AWARDS_CONTRACT

  # --- CLASS 3: LOCATION ---
  Location:
    class_uri: schema:PostalAddress
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:       # <--- The ID slot is crucial for deduplication
        identifier: true
        range: string

      country:
        slot_uri: schema:addressCountry
        required: true
        range: string

      district:
        slot_uri: schema:addressRegion
        range: string

      municipality:
        slot_uri: schema:addressLocality
        range: string
    
    slot_usage:
      BROADER:
        range: Location
    slots:
      - ADMINISTERED_BY

  # --- CLASS 4: CPV ---
  CPV:
    class_uri: skos:Concept
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:
        identifier: true
        slot_uri: skos:notation
        required: true
        range: string
        pattern: "^[0-9]{8}$"
      
      label:
        slot_uri: skos:prefLabel
        required: true
        range: string
      
      level:
        slot_uri: ext:level
        required: true
        range: string
   
    # 2. Slots (Object Properties / Links to other classes)
    slot_usage:
      BROADER:
        range: CPV

  # --- CLASS 5: DOCUMENT
  Document:
    class_uri: ocds:Document
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:
        identifier: true
        slot_uri: ocds:documentId
        required: true
        range: string
      
      document_url:
        slot_uri: schema:url
        required: true
        range: string
      
      document_description:
        slot_uri: schema:description
        range: string
  
  # --- CLASS 6: ENTITY
  Entity:
    class_uri: org:Organization
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      id:
        identifier: true
        slot_uri: org:identifier
        required: true
        range: string

      entity_name:
        slot_uri: org:name
        range: string

      valid_nif:
        slot_uri: ext:hasValidNif
        range: boolean
      

    # 2. Slots (Object Properties / Links to other classes)
    slots:
      - IS_PROCURING_ENTITY_FOR
      - IS_TENDERER_FOR
      - WON_TENDER
      - SIGNED_CONTRACT
      - LOCATED_AT
      - COMPETED_WITH
      - SHAREHOLDER_OF

      
  # --- CLASS 9: PERSON
  Person:
    class_uri: foaf:Agent
    attributes:
      id:
        identifier: true
        slot_uri: foaf:identifier
        range: string

      person_name:
        slot_uri: foaf:name
        range: string

      pep:
        slot_uri: ext:pep
        range: boolean
      

    # 2. Slots (Object Properties / Links to other classes)
    slots:
      - ASSOCIATED_WITH
      # - PARLIAMENT_MEMBER
      # - GOVERNMENT_MEMBER 
      

  #   # --- CLASS 10: PARLIAMENT
  # Parliament:
  #   class_uri: ext:Parliament
  #   attributes:
  #     id:
  #       identifier: true
  #       slot_uri: org:identifier
  #       range: string

  #     start_date:
  #       slot_uri: schema:startDate  
  #       range: date

  #     end_date:
  #       slot_uri: schema:endDate  
  #       range: date
  
  #     # --- CLASS 11: Government
  # Government:
  #   class_uri: ext:Government
  #   attributes:
  #     id:
  #       identifier: true
  #       slot_uri: org:identifier
  #       range: string

  #     start_date:
  #       slot_uri: schema:startDate  
  #       range: date

  #     end_date:
  #       slot_uri: schema:endDate  
  #       range: date



# --- GLOBAL SLOTS (Object Properties Only) ---
slots:

  AWARDS_CONTRACT:
    slot_uri: ext:AWARDS_CONTRACT    
    domain: Tender 
    range: Contract
    required: true
  
  EXECUTED_AT_LOCATION:
    slot_uri: schema:location  
    domain: Contract   
    range: Location
    inlined: true
    multivalued: true

  HAS_CPV_CLASSIFICATION:
    slot_uri: ocds:HAS_CPV_CLASSIFICATION
    domain: Contract
    range: CPV
    required: false
    multivalued: true

  BROADER:
    slot_uri: skos:BROADER
  
  HAS_DOCUMENT:
    slot_uri: ocds:hasDocument
    domain: Contract
    range: Document
    inlined: true
    multivalued: true

  IS_PROCURING_ENTITY_FOR:
    slot_uri: ocds:IS_PROCURING_ENTITY_FOR
    domain: Entity
    range: Tender
    multivalued: true

  IS_TENDERER_FOR:
    slot_uri: ocds:IS_TENDERER_FOR
    domain: Entity
    range: Tender
    multivalued: true

  WON_TENDER:
    slot_uri: ext:WON_TENDER
    domain: Entity
    range: Tender
    multivalued: true
  
  SIGNED_CONTRACT:
    slot_uri: ocds:isSignatoryForContract
    domain: Entity
    range: Contract
    multivalued: true
  
  LOCATED_AT:
    slot_uri: schema:location
    domain: Entity
    range: Location
    inlined: true
  
  COMPETED_WITH:
    slot_uri: ext:competedWith
    domain: Entity
    range: Entity
    multivalued: true

  SHAREHOLDER_OF:
    slot_uri: ext:shareholderOf
    domain: Entity
    range: Entity
    multivalued: true
  
  ADMINISTERED_BY:
    slot_uri: ext:administeredBy
    domain: Location
    range: Entity 
    multivalued: true

  ASSOCIATED_WITH:
    slot_uri: ext:ASSOCIATED_WITH
    domain: Person 
    range: Entity
    multivalued: true

  # PARLIAMENT_MEMBER: 
  #   slot_uri: org:memberOf
  #   domain: Person
  #   range: Parliament
  #   multivalued: false
  
  # GOVERNMENT_MEMBER:
  #   slot_uri: org:memberOf
  #   domain: Person
  #   range: Government
  #   multivalued: false


enums: 
  ContractTypeEnum:
    permissible_values:
      - "Concessão de obras públicas"
      - "Concessão de serviços públicos"
      - "Sociedade"
      - "Aquisição de serviços"
      - "Aquisição de bens móveis"
      - "Empreitadas de obras públicas"
      - "Locação de bens móveis"
      - "Outros Tipos"

  ProcedureTypeEnum:
    permissible_values:
      - "Concurso público simplificado"
      - "Consulta prévia ao abrigo do artigo 7º da Lei n.º 30/2021, de 21.05"
      - "Serviços sociais e outros serviços específicos"
      - "Parceria para a inovação"
      - "Consulta Prévia"
      - "Consulta Prévia Simplificada"
      - "Ajuste Direto Regime Geral ao abrigo do artigo 7º da Lei n.º 30/2021, de 21.05"
      - "Contratação excluída II"
      - "Ao abrigo de acordo-quadro (art.º 258.º)"
      - "Concurso de conceção simplificado"
      - "Setores especiais – isenção parte II"
      - "Concurso público"
      - "Ao abrigo de acordo-quadro (art.º 259.º)"
      - "Procedimento de negociação"
      - "Concurso limitado por prévia qualificação"
      - "Ajuste Direto Regime Geral"
  
  procurementMethodEnum:
    permissible_values:
      - "open"
      - "limited"
      - "selective"
      - "direct"
