COUNTRIES_SET = (
    "Espanha",
    "Franca",
    "Reino Unido",
    "Belgica",
    "Alemanha",
    "Brasil",
    "Paises Baixos",
    "Irlanda",
    "Luxemburgo",
    "Cabo Verde",
    "Angola",
    "Finlandia",
    "Canada",
    "Italia",
    "Estados Unidos",
    "Noruega",
    "Guine-Bissau",
    "Suecia",
    "Mexico",
    "Suica",
    "Eslovenia",
    "Colombia",
    "Mocambique",
    "Timor Leste",
    "Austria",
    "Dinamarca",
    "Argentina",
    "Polonia",
    "Hong Kong",
    "Egipto",
    "Tunisia",
    "China",
    "Chile",
    "Hungria",
    "Sao Tome e Principe",
    "Estonia",
    "Porto Rico",
    "Tailandia",
    "Peru",
    "Guiana Francesa",
    "Ilhas Falkland (Malvinas)",
    "India",
    "Grecia",
    "Namibia",
    "Russia (Federacao da)",
    "Coreia (Republica da)",
    "Croacia",
    "Costa do Marfim",
    "Lituania",
    "Romenia",
    "Quenia",
    "Azerbaijao",
    "Marrocos",
    "Ucrania",
    "Australia",
    "Taiwan (Provincia da China)",
    "Macau",
    "Chipre",
    "Emiratos Arabes Unidos",
    "Turquia",
    "Republica Checa"
)