DISTRICT_MUNICIPALITIES_DICT = {
    'Aveiro' : [
                "Agueda", # Águeda
                "Albergaria-a-Velha",
                "Anadia",
                "Arouca",
                "Aveiro",
                "Castelo de Paiva",
                "Espinho",
                "Estarreja",
                "Santa Maria da Feira",
                "Ilhavo",
                "Mealhada",
                "Murtosa",
                "Oliveira de Azemeis",
                "Oliveira do Bairro",
                "Ovar",
                "Sao Joao da Madeira", # São João da Madeira
                "Sever do Vouga",
                "Vagos",
                "Vale de Cambra"
                ],

    'Beja' : [
                "Aljustrel",
                "Almodovar", #Almodôvar
                "Alvito",
                "Barrancos",
                "Beja",
                "Castro Verde",
                "Cuba",
                "Ferreira do Alentejo",
                "Mertola", # Mértola
                "Moura",
                "Odemira",
                "Ourique",
                "Serpa",
                "Vidigueira"
                ], 
    'Braga' : [
                "Amares",
                "Barcelos",
                "Braga",
                "Cabeceiras de Basto",
                "Celorico de Basto",
                "Esposende",
                "Fafe",
                "Guimaraes", # Guimarães
                "Povoa de Lanhoso", # Póvoa de Lanhoso
                "Terras de Bouro",
                "Vieira do Minho",
                "Vila Nova de Famalicao", # Vila Nova de Famalicão
                "Vila Verde",
                "Vizela"
                ],
    'Braganca' : [ # Bragança
                "Alfandega da Fe", # Alfândega da Fé
                "Braganca", # Bragança
                "Carrazeda de Ansiaes", # Carrazeda de Ansiães
                "Freixo Espada a Cinta", # Freixo Espada à Cinta
                "Macedo de Cavaleiros",
                "Miranda do Douro",
                "Mirandela",
                "Mogadouro",
                "Torre de Moncorvo",
                "Vila Flor",
                "Vimioso",
                "Vinhais"
                ],
    'Castelo Branco' : [
                "Belmonte",
                "Castelo Branco",
                "Covilha", # Covilhã
                "Fundao", # Fundão
                "Idanha-a-Nova",
                "Oleiros",
                "Penamacor",
                "Proenca-a-Nova", # Proença-a-Nova
                "Serta", # Sertã
                "Vila de Rei",
                "Vila Velha de Rodao" # Vila Velha de Ródão
                ],
    'Coimbra' : [
                "Arganil",
                "Cantanhede",
                "Coimbra",
                "Condeixa-a-Nova",
                "Figueira da Foz",
                "Gois", # Góis
                "Lousa", # Lousã
                "Mira",
                "Miranda do Corvo",
                "Montemor-o-Velho",
                "Oliveira do Hospital",
                "Pampilhosa da Serra",
                "Penacova",
                "Penela",
                "Soure",
                "Tabua", # Tábua
                "Vila Nova de Poiares"
                ],  
    'Evora' : [ # Évora
                "Alandroal",
                "Arraiolos",
                "Borba",
                "Estremoz",
                "Evora", # Évora
                "Montemor-o-Novo",
                "Mora",
                "Mourao", # Mourão
                "Portel",
                "Redondo",
                "Reguengos de Monsaraz",
                "Vendas Novas",
                "Viana do Alentejo",
                "Vila Vicosa" # Vila Viçosa
                ],
    'Faro' : [
                "Albufeira",
                "Alcoutim",
                "Aljezur",
                "Castro Marim",
                "Faro",
                "Lagoa",
                "Lagos",
                "Loule", # Loulé
                "Monchique",
                "Olhao", # Olhão
                "Portimao", # Portimão
                "Sao Bras de Alportel", # São Brás de Alportel
                "Silves",
                "Tavira",
                "Vila do Bispo",
                "Vila Real Sto Antonio" # Vila Real de Sto Antonio
                ],
    'Guarda' : [
                "Aguiar da Beira",
                "Almeida",
                "Celorico da Beira",
                "Fig. Castelo Rodrigo",
                "Fornos de Algodres",
                "Gouveia",
                "Guarda",
                "Manteigas",
                "Meda",
                "Pinhel",
                "Sabugal",
                "Seia",
                "Trancoso", 
                "Vila Nova de Foz Coa" 
                ],
    'Leiria' : [
                "Alcobaca", # Alcobaça
                "Alvaiazere", # Alvaiázere
                "Ansiao", # Ansião
                "Batalha",
                "Bombarral",
                "Caldas da Rainha",
                "Castanheira de Pera",
                "Figueiro dos Vinhos", # Figueiró dos Vinhos
                "Leiria",
                "Marinha Grande",
                "Nazare", # Nazaré  
                "Obidos", # Óbidos
                "Pedrogao Grande", # Pedrógão Grande
                "Peniche",
                "Pombal",
                "Porto de Mos" # Porto de Mós
                ],
    'Lisboa' : [
                "Alenquer",
                "Amadora",
                "Arruda dos Vinhos",
                "Azambuja",
                "Cadaval",
                "Cascais",
                "Lisboa",
                "Loures",
                "Lourinha", # Lourinhã
                "Mafra",
                "Odivelas",
                "Oeiras",
                "Sintra",
                "Sobral de Monte Agraco", # Sobral de Monte Agraço
                "Torres Vedras",
                "Vila Franca de Xira"
                ],
    'Portalegre' : [
                "Alter do Chao", # Alter do Chão
                "Arronches",
                "Avis",
                "Campo Maior",
                "Castelo de Vide",
                "Crato",
                "Elvas",
                "Fronteira",
                "Gaviao", # Gavião
                "Marvao", # Marvão
                "Monforte",
                "Nisa",
                "Portalegre",
                "Ponte de Sor",
                "Sousel"
                ],
    'Porto' : [
                "Amarante",
                "Baiao", # Baião
                "Felgueiras",
                "Gondomar",
                "Lousada",
                "Maia",
                "Marco de Canaveses",
                "Matosinhos",
                "Pacos de Ferreira", #Paços de Ferreira
                "Paredes",
                "Penafiel",
                "Porto",
                "Povoa de Varzim", # Póvoa de Varzim
                "Santo Tirso",
                "Valongo",
                "Vila do Conde",
                "Vila Nova de Gaia",
                "Trofa",
                ],
    'Santarem' : [# Santarém
                "Abrantes",
                "Alcanena",
                "Almeirim",
                "Alpiarca", # Alpiarça
                "Benavente",
                "Cartaxo",
                "Chamusca",
                "Constancia",
                "Coruche",
                "Entroncamento",
                "Ferreira do Zezere",
                "Golega", # Golegã
                "Macao", # Mação
                "Rio Maior",
                "Salvaterra de Magos",
                "Santarem", # Santarém
                "Sardoal",
                "Tomar",
                "Torres Novas",
                "Vila Nova da Barquinha",
                "Ourem" # Ourém
                ],
    'Setubal' : [ # Setúbal
                "Alcacer do Sal", # Alcácer do Sal
                "Alcochete",
                "Almada",
                "Barreiro",
                "Grandola",
                "Moita",
                "Montijo",
                "Palmela",
                "Santiago do Cacem", # Santiago do Cacém
                "Seixal",
                "Sesimbra",
                "Setubal", # Setúbal
                "Sines"
                ],
    'Viana do Castelo' : [
                "Arcos de Valdevez",
                "Caminha",
                "Melgaco", # Melgaço
                "Moncao", # Monção
                "Paredes de Coura",
                "Ponte da Barca",
                "Ponte de Lima",
                "Valenca", # Valença
                "Viana do Castelo",
                "Vila Nova de Cerveira"
                ],
    'Vila Real' : [
                "Alijo", # Alijó
                "Boticas",
                "Chaves",
                "Mesao Frio", # Mesão Frio
                "Mondim de Basto",
                "Montalegre",
                "Murca", # Murça
                "Peso da Regua", # Peso da Régua
                "Ribeira de Pena",
                "Sabrosa",
                "Sta Marta de Penaguiao", # Santa Marta de Penaguião
                "Valpacos", # Valpaços
                "Vila Pouca de Aguiar",
                "Vila Real"
                ],
    'Viseu' : [
                "Armamar",
                "Carregal do Sal",
                "Castro Daire",
                "Cinfaes", # Cinfães
                "Lamego",
                "Mangualde",
                "Moimenta da Beira",
                "Mortagua", # Mortágua
                "Nelas",
                "Oliveira de Frades",
                "Penalva do Castelo",
                "Penedono",
                "Resende",
                "Santa Comba Dao", # Santa Comba Dão
                "Sao Joao da Pesqueira", # São João da Pesqueira
                "Sao Pedro do Sul", # São Pedro do Sul
                "Satao", # Sátão
                "Sernancelhe",
                "Tabuaco", # Tabuaço
                "Tarouca",
                "Tondela",
                "Vila Nova de Paiva",
                "Viseu",
                "Vouzela"
                ],

    "Regiao Autonoma dos Acores": [ # Regiao Autonoma dos Acores
                "Angra do Heroismo", #
                "Calheta",
                "Santa Cruz da Graciosa",
                "Velas",
                "Praia da Vitoria", # Praia da Vitória
                "Corvo",
                "Horta",
                "Lajes das Flores",
                "Lajes do Pico",
                "Madalena",
                "Santa Cruz das Flores",
                "Sao Roque do Pico", # São Roque do Pico
                "Lagoa",
                "Nordeste",
                "Ponta Delgada",
                "Povoacao", # Povoação
                "Ribeira Grande",
                "Vila Franca do Campo",
                "Vila do Porto"
            ],
    "Regiao Autonoma da Madeira": [
                "Calheta",
                "Camara de Lobos", # Câmara de Lobos
                "Funchal",
                "Machico",
                "Ponta do Sol",
                "Porto Moniz",
                "Porto Santo",
                "Ribeira Brava",
                "Santa Cruz",
                "Santana",
                "Sao Vicente" # São Vicente
            ]
}



MUNICIPALITY_LOOKUP = {'Agueda': ('Portugal', 'Aveiro'),
 'Albergaria-a-Velha': ('Portugal', 'Aveiro'),
 'Anadia': ('Portugal', 'Aveiro'),
 'Arouca': ('Portugal', 'Aveiro'),
 'Aveiro': ('Portugal', 'Aveiro'),
 'Castelo de Paiva': ('Portugal', 'Aveiro'),
 'Espinho': ('Portugal', 'Aveiro'),
 'Estarreja': ('Portugal', 'Aveiro'),
 'Santa Maria da Feira': ('Portugal', 'Aveiro'),
 'Ilhavo': ('Portugal', 'Aveiro'),
 'Mealhada': ('Portugal', 'Aveiro'),
 'Murtosa': ('Portugal', 'Aveiro'),
 'Oliveira de Azemeis': ('Portugal', 'Aveiro'),
 'Oliveira do Bairro': ('Portugal', 'Aveiro'),
 'Ovar': ('Portugal', 'Aveiro'),
 'Sao Joao da Madeira': ('Portugal', 'Aveiro'),
 'Sever do Vouga': ('Portugal', 'Aveiro'),
 'Vagos': ('Portugal', 'Aveiro'),
 'Vale de Cambra': ('Portugal', 'Aveiro'),
 'Aljustrel': ('Portugal', 'Beja'),
 'Almodovar': ('Portugal', 'Beja'),
 'Alvito': ('Portugal', 'Beja'),
 'Barrancos': ('Portugal', 'Beja'),
 'Beja': ('Portugal', 'Beja'),
 'Castro Verde': ('Portugal', 'Beja'),
 'Cuba': ('Portugal', 'Beja'),
 'Ferreira do Alentejo': ('Portugal', 'Beja'),
 'Mertola': ('Portugal', 'Beja'),
 'Moura': ('Portugal', 'Beja'),
 'Odemira': ('Portugal', 'Beja'),
 'Ourique': ('Portugal', 'Beja'),
 'Serpa': ('Portugal', 'Beja'),
 'Vidigueira': ('Portugal', 'Beja'),
 'Amares': ('Portugal', 'Braga'),
 'Barcelos': ('Portugal', 'Braga'),
 'Braga': ('Portugal', 'Braga'),
 'Cabeceiras de Basto': ('Portugal', 'Braga'),
 'Celorico de Basto': ('Portugal', 'Braga'),
 'Esposende': ('Portugal', 'Braga'),
 'Fafe': ('Portugal', 'Braga'),
 'Guimaraes': ('Portugal', 'Braga'),
 'Povoa de Lanhoso': ('Portugal', 'Braga'),
 'Terras de Bouro': ('Portugal', 'Braga'),
 'Vieira do Minho': ('Portugal', 'Braga'),
 'Vila Nova de Famalicao': ('Portugal', 'Braga'),
 'Vila Verde': ('Portugal', 'Braga'),
 'Vizela': ('Portugal', 'Braga'),
 'Alfandega da Fe': ('Portugal', 'Braganca'),
 'Braganca': ('Portugal', 'Braganca'),
 'Carrazeda de Ansiaes': ('Portugal', 'Braganca'),
 'Freixo Espada a Cinta': ('Portugal', 'Braganca'),
 'Macedo de Cavaleiros': ('Portugal', 'Braganca'),
 'Miranda do Douro': ('Portugal', 'Braganca'),
 'Mirandela': ('Portugal', 'Braganca'),
 'Mogadouro': ('Portugal', 'Braganca'),
 'Torre de Moncorvo': ('Portugal', 'Braganca'),
 'Vila Flor': ('Portugal', 'Braganca'),
 'Vimioso': ('Portugal', 'Braganca'),
 'Vinhais': ('Portugal', 'Braganca'),
 'Belmonte': ('Portugal', 'Castelo Branco'),
 'Castelo Branco': ('Portugal', 'Castelo Branco'),
 'Covilha': ('Portugal', 'Castelo Branco'),
 'Fundao': ('Portugal', 'Castelo Branco'),
 'Idanha-a-Nova': ('Portugal', 'Castelo Branco'),
 'Oleiros': ('Portugal', 'Castelo Branco'),
 'Penamacor': ('Portugal', 'Castelo Branco'),
 'Proenca-a-Nova': ('Portugal', 'Castelo Branco'),
 'Serta': ('Portugal', 'Castelo Branco'),
 'Vila de Rei': ('Portugal', 'Castelo Branco'),
 'Vila Velha de Rodao': ('Portugal', 'Castelo Branco'),
 'Arganil': ('Portugal', 'Coimbra'),
 'Cantanhede': ('Portugal', 'Coimbra'),
 'Coimbra': ('Portugal', 'Coimbra'),
 'Condeixa-a-Nova': ('Portugal', 'Coimbra'),
 'Figueira da Foz': ('Portugal', 'Coimbra'),
 'Gois': ('Portugal', 'Coimbra'),
 'Lousa': ('Portugal', 'Coimbra'),
 'Mira': ('Portugal', 'Coimbra'),
 'Miranda do Corvo': ('Portugal', 'Coimbra'),
 'Montemor-o-Velho': ('Portugal', 'Coimbra'),
 'Oliveira do Hospital': ('Portugal', 'Coimbra'),
 'Pampilhosa da Serra': ('Portugal', 'Coimbra'),
 'Penacova': ('Portugal', 'Coimbra'),
 'Penela': ('Portugal', 'Coimbra'),
 'Soure': ('Portugal', 'Coimbra'),
 'Tabua': ('Portugal', 'Coimbra'),
 'Vila Nova de Poiares': ('Portugal', 'Coimbra'),
 'Alandroal': ('Portugal', 'Evora'),
 'Arraiolos': ('Portugal', 'Evora'),
 'Borba': ('Portugal', 'Evora'),
 'Estremoz': ('Portugal', 'Evora'),
 'Evora': ('Portugal', 'Evora'),
 'Montemor-o-Novo': ('Portugal', 'Evora'),
 'Mora': ('Portugal', 'Evora'),
 'Mourao': ('Portugal', 'Evora'),
 'Portel': ('Portugal', 'Evora'),
 'Redondo': ('Portugal', 'Evora'),
 'Reguengos de Monsaraz': ('Portugal', 'Evora'),
 'Vendas Novas': ('Portugal', 'Evora'),
 'Viana do Alentejo': ('Portugal', 'Evora'),
 'Vila Vicosa': ('Portugal', 'Evora'),
 'Albufeira': ('Portugal', 'Faro'),
 'Alcoutim': ('Portugal', 'Faro'),
 'Aljezur': ('Portugal', 'Faro'),
 'Castro Marim': ('Portugal', 'Faro'),
 'Faro': ('Portugal', 'Faro'),
 'Lagoa': 'AMBIGUOUS',
 'Lagos': ('Portugal', 'Faro'),
 'Loule': ('Portugal', 'Faro'),
 'Monchique': ('Portugal', 'Faro'),
 'Olhao': ('Portugal', 'Faro'),
 'Portimao': ('Portugal', 'Faro'),
 'Sao Bras de Alportel': ('Portugal', 'Faro'),
 'Silves': ('Portugal', 'Faro'),
 'Tavira': ('Portugal', 'Faro'),
 'Vila do Bispo': ('Portugal', 'Faro'),
 'Vila Real Sto Antonio': ('Portugal', 'Faro'),
 'Aguiar da Beira': ('Portugal', 'Guarda'),
 'Almeida': ('Portugal', 'Guarda'),
 'Celorico da Beira': ('Portugal', 'Guarda'),
 'Fig. Castelo Rodrigo': ('Portugal', 'Guarda'),
 'Fornos de Algodres': ('Portugal', 'Guarda'),
 'Gouveia': ('Portugal', 'Guarda'),
 'Guarda': ('Portugal', 'Guarda'),
 'Manteigas': ('Portugal', 'Guarda'),
 'Meda': ('Portugal', 'Guarda'),
 'Pinhel': ('Portugal', 'Guarda'),
 'Sabugal': ('Portugal', 'Guarda'),
 'Seia': ('Portugal', 'Guarda'),
 'Trancoso': ('Portugal', 'Guarda'),
 'Vila Nova de Foz Coa': ('Portugal', 'Guarda'),
 'Alcobaca': ('Portugal', 'Leiria'),
 'Alvaiazere': ('Portugal', 'Leiria'),
 'Ansiao': ('Portugal', 'Leiria'),
 'Batalha': ('Portugal', 'Leiria'),
 'Bombarral': ('Portugal', 'Leiria'),
 'Caldas da Rainha': ('Portugal', 'Leiria'),
 'Castanheira de Pera': ('Portugal', 'Leiria'),
 'Figueiro dos Vinhos': ('Portugal', 'Leiria'),
 'Leiria': ('Portugal', 'Leiria'),
 'Marinha Grande': ('Portugal', 'Leiria'),
 'Nazare': ('Portugal', 'Leiria'),
 'Obidos': ('Portugal', 'Leiria'),
 'Pedrogao Grande': ('Portugal', 'Leiria'),
 'Peniche': ('Portugal', 'Leiria'),
 'Pombal': ('Portugal', 'Leiria'),
 'Porto de Mos': ('Portugal', 'Leiria'),
 'Alenquer': ('Portugal', 'Lisboa'),
 'Amadora': ('Portugal', 'Lisboa'),
 'Arruda dos Vinhos': ('Portugal', 'Lisboa'),
 'Azambuja': ('Portugal', 'Lisboa'),
 'Cadaval': ('Portugal', 'Lisboa'),
 'Cascais': ('Portugal', 'Lisboa'),
 'Lisboa': ('Portugal', 'Lisboa'),
 'Loures': ('Portugal', 'Lisboa'),
 'Lourinha': ('Portugal', 'Lisboa'),
 'Mafra': ('Portugal', 'Lisboa'),
 'Odivelas': ('Portugal', 'Lisboa'),
 'Oeiras': ('Portugal', 'Lisboa'),
 'Sintra': ('Portugal', 'Lisboa'),
 'Sobral de Monte Agraco': ('Portugal', 'Lisboa'),
 'Torres Vedras': ('Portugal', 'Lisboa'),
 'Vila Franca de Xira': ('Portugal', 'Lisboa'),
 'Alter do Chao': ('Portugal', 'Portalegre'),
 'Arronches': ('Portugal', 'Portalegre'),
 'Avis': ('Portugal', 'Portalegre'),
 'Campo Maior': ('Portugal', 'Portalegre'),
 'Castelo de Vide': ('Portugal', 'Portalegre'),
 'Crato': ('Portugal', 'Portalegre'),
 'Elvas': ('Portugal', 'Portalegre'),
 'Fronteira': ('Portugal', 'Portalegre'),
 'Gaviao': ('Portugal', 'Portalegre'),
 'Marvao': ('Portugal', 'Portalegre'),
 'Monforte': ('Portugal', 'Portalegre'),
 'Nisa': ('Portugal', 'Portalegre'),
 'Portalegre': ('Portugal', 'Portalegre'),
 'Ponte de Sor': ('Portugal', 'Portalegre'),
 'Sousel': ('Portugal', 'Portalegre'),
 'Amarante': ('Portugal', 'Porto'),
 'Baiao': ('Portugal', 'Porto'),
 'Felgueiras': ('Portugal', 'Porto'),
 'Gondomar': ('Portugal', 'Porto'),
 'Lousada': ('Portugal', 'Porto'),
 'Maia': ('Portugal', 'Porto'),
 'Marco de Canaveses': ('Portugal', 'Porto'),
 'Matosinhos': ('Portugal', 'Porto'),
 'Pacos de Ferreira': ('Portugal', 'Porto'),
 'Paredes': ('Portugal', 'Porto'),
 'Penafiel': ('Portugal', 'Porto'),
 'Porto': ('Portugal', 'Porto'),
 'Povoa de Varzim': ('Portugal', 'Porto'),
 'Santo Tirso': ('Portugal', 'Porto'),
 'Valongo': ('Portugal', 'Porto'),
 'Vila do Conde': ('Portugal', 'Porto'),
 'Vila Nova de Gaia': ('Portugal', 'Porto'),
 'Trofa': ('Portugal', 'Porto'),
 'Abrantes': ('Portugal', 'Santarem'),
 'Alcanena': ('Portugal', 'Santarem'),
 'Almeirim': ('Portugal', 'Santarem'),
 'Alpiarca': ('Portugal', 'Santarem'),
 'Benavente': ('Portugal', 'Santarem'),
 'Cartaxo': ('Portugal', 'Santarem'),
 'Chamusca': ('Portugal', 'Santarem'),
 'Constancia': ('Portugal', 'Santarem'),
 'Coruche': ('Portugal', 'Santarem'),
 'Entroncamento': ('Portugal', 'Santarem'),
 'Ferreira do Zezere': ('Portugal', 'Santarem'),
 'Golega': ('Portugal', 'Santarem'),
 'Macao': ('Portugal', 'Santarem'),
 'Rio Maior': ('Portugal', 'Santarem'),
 'Salvaterra de Magos': ('Portugal', 'Santarem'),
 'Santarem': ('Portugal', 'Santarem'),
 'Sardoal': ('Portugal', 'Santarem'),
 'Tomar': ('Portugal', 'Santarem'),
 'Torres Novas': ('Portugal', 'Santarem'),
 'Vila Nova da Barquinha': ('Portugal', 'Santarem'),
 'Ourem': ('Portugal', 'Santarem'),
 'Alcacer do Sal': ('Portugal', 'Setubal'),
 'Alcochete': ('Portugal', 'Setubal'),
 'Almada': ('Portugal', 'Setubal'),
 'Barreiro': ('Portugal', 'Setubal'),
 'Grandola': ('Portugal', 'Setubal'),
 'Moita': ('Portugal', 'Setubal'),
 'Montijo': ('Portugal', 'Setubal'),
 'Palmela': ('Portugal', 'Setubal'),
 'Santiago do Cacem': ('Portugal', 'Setubal'),
 'Seixal': ('Portugal', 'Setubal'),
 'Sesimbra': ('Portugal', 'Setubal'),
 'Setubal': ('Portugal', 'Setubal'),
 'Sines': ('Portugal', 'Setubal'),
 'Arcos de Valdevez': ('Portugal', 'Viana do Castelo'),
 'Caminha': ('Portugal', 'Viana do Castelo'),
 'Melgaco': ('Portugal', 'Viana do Castelo'),
 'Moncao': ('Portugal', 'Viana do Castelo'),
 'Paredes de Coura': ('Portugal', 'Viana do Castelo'),
 'Ponte da Barca': ('Portugal', 'Viana do Castelo'),
 'Ponte de Lima': ('Portugal', 'Viana do Castelo'),
 'Valenca': ('Portugal', 'Viana do Castelo'),
 'Viana do Castelo': ('Portugal', 'Viana do Castelo'),
 'Vila Nova de Cerveira': ('Portugal', 'Viana do Castelo'),
 'Alijo': ('Portugal', 'Vila Real'),
 'Boticas': ('Portugal', 'Vila Real'),
 'Chaves': ('Portugal', 'Vila Real'),
 'Mesao Frio': ('Portugal', 'Vila Real'),
 'Mondim de Basto': ('Portugal', 'Vila Real'),
 'Montalegre': ('Portugal', 'Vila Real'),
 'Murca': ('Portugal', 'Vila Real'),
 'Peso da Regua': ('Portugal', 'Vila Real'),
 'Ribeira de Pena': ('Portugal', 'Vila Real'),
 'Sabrosa': ('Portugal', 'Vila Real'),
 'Sta Marta de Penaguiao': ('Portugal', 'Vila Real'),
 'Valpacos': ('Portugal', 'Vila Real'),
 'Vila Pouca de Aguiar': ('Portugal', 'Vila Real'),
 'Vila Real': ('Portugal', 'Vila Real'),
 'Armamar': ('Portugal', 'Viseu'),
 'Carregal do Sal': ('Portugal', 'Viseu'),
 'Castro Daire': ('Portugal', 'Viseu'),
 'Cinfaes': ('Portugal', 'Viseu'),
 'Lamego': ('Portugal', 'Viseu'),
 'Mangualde': ('Portugal', 'Viseu'),
 'Moimenta da Beira': ('Portugal', 'Viseu'),
 'Mortagua': ('Portugal', 'Viseu'),
 'Nelas': ('Portugal', 'Viseu'),
 'Oliveira de Frades': ('Portugal', 'Viseu'),
 'Penalva do Castelo': ('Portugal', 'Viseu'),
 'Penedono': ('Portugal', 'Viseu'),
 'Resende': ('Portugal', 'Viseu'),
 'Santa Comba Dao': ('Portugal', 'Viseu'),
 'Sao Joao da Pesqueira': ('Portugal', 'Viseu'),
 'Sao Pedro do Sul': ('Portugal', 'Viseu'),
 'Satao': ('Portugal', 'Viseu'),
 'Sernancelhe': ('Portugal', 'Viseu'),
 'Tabuaco': ('Portugal', 'Viseu'),
 'Tarouca': ('Portugal', 'Viseu'),
 'Tondela': ('Portugal', 'Viseu'),
 'Vila Nova de Paiva': ('Portugal', 'Viseu'),
 'Viseu': ('Portugal', 'Viseu'),
 'Vouzela': ('Portugal', 'Viseu'),
 'Angra do Heroismo': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Calheta': 'AMBIGUOUS',
 'Santa Cruz da Graciosa': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Velas': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Praia da Vitoria': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Corvo': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Horta': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Lajes das Flores': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Lajes do Pico': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Madalena': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Santa Cruz das Flores': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Sao Roque do Pico': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Nordeste': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Ponta Delgada': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Povoacao': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Ribeira Grande': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Vila Franca do Campo': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Vila do Porto': ('Portugal', 'Regiao Autonoma dos Acores'),
 'Camara de Lobos': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Funchal': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Machico': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Ponta do Sol': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Porto Moniz': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Porto Santo': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Ribeira Brava': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Santa Cruz': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Santana': ('Portugal', 'Regiao Autonoma da Madeira'),
 'Sao Vicente': ('Portugal', 'Regiao Autonoma da Madeira')}