OCC_TO_BASE_ENTITY_MAP = {
    
    'Vitrus Ambiente': ('Vitrus Ambiente, E.M., S.A.', 509584888),
 'Varzim Lazer': ('Varzim Lazer - Empresa Municipal de Gestão de Equipamentos Desportivos e de Lazer, E.E.M.',
  504841700),
 'Coliseu Micaelense - Soc. Prom. Eventos Culturais': ('Coliseu Micaelense, SA',
  512059420),
 'Amadora Inovation': ('Amadora Inovation, E. M., Unipessoal, L.da',
  504746383),
 'EGEAC - Gest. Equipam. e Animação Cultural': ('EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, EEM',
  503584215),
 'Termalistur - Termas': ('Termalistur - Termas de S. Pedro do Sul, E.E.M.',
  506817997),
 'EMES - Estacionamento': ('EMES - Empresa Municipal de Estacionamento de Sintra, E. M.',
  504610163),
 'SMAS Torres Vedras': ('SMAS TORRES VEDRAS', 680015973),
 'Nazaré Qualifica': ('Nazaré Qualifica, E.M., Unipessoal, Lda.', 507571053),
 'Empresa Municipal de Ambiente do Porto': ('Empresa Municipal de Ambiente do Porto E. M. S. A.',
  514280956),
 'Oeiras Viva\ue02dGestão Equip. Sócio Cult. e Desp.': ('Oeiras Viva - Gestão de Equipamentos Sócio Culturais e Desportivos E. M.',
  505351064),
 'Lousada Seculo XXI': ('Lousada Século XXI - Actividades Desportivas e Recreativas - E. M., Sociedade Unipessoal, L.da',
  505840464),
 'Teatro Municipal de Faro - SM': ('TEATRO MUNICIPAL DE FARO-SM', 600086305),
 'AMBIOLHÃO\ue02dEM de Ambiente de Olhão': ('Ambiolhão - Empresa Municipal de Ambiente de Olhão EM',
  509680780),
 'SMAS de Mafra': ('Serviços Municipalizados de Águas e Saneamento de Mafra - SMAS de Mafra',
  600087247),
 'Pmugest - Pombal Manutenção Urbana': ('PMU - POMBAL, MANUTENÇÃO URBANA, E.M.',
  505214300),
 'EMEM - Emp. Metropolitana Estacionamento': ('Empresa Metropolitana de Estacionamento da Maia, EEM',
  504830783),
 'TUMG - Transportes Urbanos': ('TUMG - Transportes Urbanos da Marinha Grande E. M. Unipessoal S. A.',
  505849348),
 'ACLEM - Arte, Cultura e Lazer': ('ACLEM - Arte, Cultura e Lazer, Empresa Municipal, E.M.',
  507974530),
 'Centro Estudos e Form. Prof. Diogo Dias Melgaz': ('Centro de Estudos e Formação Prof Diogo Dias Melgaz',
  508581303),
 'Gaiurb - Urbanismo e Habitação': ('Gaiurb - Urbanismo e Habitação, E.E.M.',
  506064433),
 'Espaço Municipal - Renov. Urb.e Gestão Patrim.': ('Espaço Municipal - Renovação Urbana e Gestão do Património, SA',
  505462583),
 'GEBALIS - Gest. Bairros Municipais Lisboa': ('Gebalis', 503541567),
 'Melsport - Melgaço Desporto e Lazer': ('Melsport-Melgaço desporto e Lazer, EM',
  505922274),
 'TEGEC - Gest. Equip. Culturais e de Lazer': ('T.E.G.E.G. TRANCOSO EVENTOS, EMPRESA MUNICIPAL DE GESTÃO DE EQUIPAMENTOS CULTURAIS E DE LAZER, E.M.',
  505391414),
 'ProRuris - EM de Desenvolv. Rural de Vinhais': ('PRORURIS - EMPRESA MUNICIPAL DE DESENVOLVIMENTO RURAL DE VINHAIS, E.E.M',
  507643720),
 'EPAVE - Escola Profissional do Alto Ave': ('EPAVE - Escola Profissional do Alto Ave, E. M.',
  504596608),
 'Promotorres - Prom. Eventos e Gest. Equip.': ('PROMOTORRES ', 503941565),
 'AC Aguas de Coimbra': ('AC, Aguas de Coimbra', 506566307),
 'Viverfundão': ('Viverfundão - Promoção e Gestão das Condições Estruturais e Infraestruturais para o concelho do Fundão',
  507197895),
 'ABMG - Águas do Baixo Mondego e Gândara': ('ABMG - Águas do Baixo Mondego e Gândara, E. I. M., S. A.',
  515620491),
 'BRAGAHABIT - Habitação': ('BRAGAHABIT - Empresa Municipal de Habitação de Braga E. M.',
  504537784),
 'APDSE - Águas Públicas da Serra da Estrela': ('Águas Públicas da Serra da Estrela, E. I. M., S. A.',
  515957631),
 'AQUANENA': ('AQUANENA - Empresa Municipal de Águas e Saneamento de Alcanena, E. M., S. A.',
  515194212),
 'EMPDS - Promoção e Desenvolv. Social': ('EMPDS, EM', 506779360),
 'Viver Santarém': ('Viver Santarém - Desporto e Lazer, E. M., S. A.',
  506159540),
 'Quintas de Melgaço': ('Quintas de Melgaço – Agricultura e Turismo, S.A',
  502476397),
 'AGERE - Águas, Efluentes e Resíduos': ('AGERE - Empresa de Água, Efluentes e Resíduos de Braga, EM',
  504807692),
 'Habisolvis - Habitação Social': ('HABISOLVIS - Empresa Municipal de Habitação Social de Viseu, EM',
  506804186),
 'TML - Transportes Metropolitanos de Lisboa': ('TML - Transportes Metropolitanos de Lisboa, E. M. T., S. A.',
  516150359),
 'EPRM - Escola Profissional de Rio Maior': ('EPRM - Escola Profissional de Rio Maior, Lda',
  504617656),
 'VRS - Vila Real Social': ('Vila Real Social - Habitação E. E. M.',
  506376745),
 'Teatro Circo de Braga': ('Teatro Circo de Braga, EM, S.A.', 500463964),
 'Gestão de Obras Públicas da CM do Porto': ('Gestão de Obras Públicas da Câmara Municipal do Porto, EM',
  505037238),
 'PRODESO - Ensino Profissional': ('Prodeso - Ensino Profissional, L.D.A',
  502675870),
 'EPF - Ensino Profissional de Felgueiras': ('E. P. F. - Ensino Profissional de Felgueiras, E. M., Unipessoal, L.da',
  504575848),
 'AIN - Agro\ue02dIndustrial do Nordeste': ('AIN – Agro-industrial do nordeste, EIM, SA',
  503193259),
 'Emp. Transportes Colectivos da Ilha Graciosa': ('Empresa de Transportes Colectivos da Graciosa, Lda.',
  512006156),
 'Parques Tejo - Parqueamentos de Oeiras': ('Parques Tejo Parqueamentos de Oeiras, E.M.',
  504719670),
 'Urbhorta': ('UrbHorta - Construção, Gestão e Exploração de Desenvolvimento Empresarial EEM',
  512090084),
 'SMTC - Transp. Colectivos do Barreiro': ('Serviços Municipalizados Transportes Colectivos Barreiro',
  680015574),
 'Matosinhoshabit - Habitação de Matosinhos': ('Matosinhoshabit-MH Empresa Municipal de Habitação de Matosinhos E. M.',
  504597221),
 'INOVA - Emp. Desenv. Ecom. e Social': ('Inova-Emp.Des.Eco.Soc.Canta.Em',
  506091481),
 'Parkurbis, Parque de Ciência e Tecn. Covilhã': ('PARKURBIS - Parque de Ciência e Tecnologia da Covilhã, SA',
  505456176),
 'EMEL - EPM de Mobilidade e Estacionamento': ('Emel -Empresa Municipal de Mobilidade e Estacionamento de Lisboa, E.M., S.A.',
  503311332),
 'SMAS de Almada': ('SMAS - MUNICIPIO DE ALMADA', 680017763),
 'Águas de Santarém': ('A.S.-Empresa das Águas de Santarém', 508114381),
 'Cidade em Acção': ('Cidade em Acção - Sociedade de Desenvolvimento e Gestão de Equipamentos Urbanos, S. A.',
  512088845),
 'Feira Viva Cultura e Desporto': ('Feira Viva - Cultura e Desporto, E.E.M',
  505120151),
 'SMAS de Caldas da Rainha': ('SMAS - CALDAS RAINHA ', 680001069),
 'Palmela Desporto': ('Palmela Desporto Empresa Municipal de Gestão de Espaços e Equipamentos Desportivos Municipais, EM',
  504706675),
 'EMAS - EM de Água e Saneamento de Beja': ('EMAS', 505991527),
 'Penafiel Activa': ('Penafiel Activa, EM', 506196917),
 'Infratroia - Infraestruturas': ('INFRATRÓIA - Infraestruturas de Tróia, E. M.',
  505263963),
 'Lisboa Ocidental, SRU': ('Lisboa Ocidental SRU - Sociedade de Reabilitação Urbana, E.E.M.',
  507023129),
 'Loures Parque - Estacionamento': ('Loures Parque', 505072947),
 'Aveiro Expo - Parque de Exposições': ('Aveiro Expo - Parque de Exposições, E.M.',
  507095677),
 'EAMB - Esposende Ambiente': ('EAmb - Esposende Ambiente, EEM', 507068076),
 'ICOVI - Infraestruturas e Concessões': ('ICOVI - Infraestruturas e Concessões da Covilhã, E.E.M.',
  508282322),
 'Óbidos Criativa': ('Óbidos Criativa, E. M.', 507566343),
 'Cura Aquae\ue02dTermas de Melgaço': ('Cura Aquae - Termas de Melgaço E. M.',
  509688373),
 'FAGAR - Faro Gestão de Aguas e Resíduos': ('Fagar - Faro, Gestão de Água e Residuos, E. M.',
  507142217),
 'EMARP - Águas e Residuos de Portimão': ('Empresa Municipal de Aguas e Residuos de Portimão',
  505322730),
 'ALBIGEC': ('Albigec - Empresa de Gestão de Equipamentos, Culturais, Desportivos e de Lazer, E. M.',
  505715449),
 'SMAS do Montijo': ('SMAS MONTIJO', 680047930),
 'Ensino Profissional de Tomar': ('EPT - Ensino Profissional de Tomar, L.da',
  504699326),
 'SMAS de Peniche': ('SMAS PENICHE', 680019600),
 'Frente MarFunchal': ('Frente MarFunchal - Gestão e Exploração de Espaços Públicos e de Estacionamentos Públicos Urbanos do Funchal, E. M.',
  511233744),
 'Lagos\ue02dem\ue02dForma -  Gestão Desportiva': ('Lagos em Forma,SA',
  507725077),
 'Quinta de Tuberais - Ensino Prof. de Cinfães': ('Quinta de Tuberais - Ensino Profissional de Cinfães, E. M.',
  504615858),
 'Sociohabitafunchal': ('SOCIOHABITAFUNCHAL - Empresa Municipal de Habitação, E. M.',
  511237880),
 'CASFIG - Coordenação das Habitações': ('CASFIG, E.M.', 504885855),
 'Companhia Carris de Ferro de Lisboa': ('Companhia Carris de Ferro Lisboa',
  500595313),
 'Mercados de Olhão': ('Mercados de Olhão, E. E. M.', 504288865),
 'Águas de Gaia': ('Àguas e Parque Biológico de Gaia, E.E.M.', 504763202),
 'RIBEIRAPERA': ('Ribeirapera - Sociedade para o Desenvolvimento de Castanheira de Pera, E.M.,S.A.',
  501452303),
 'Cascais Envolvente': ('Cascais Envolvente -  Gestão Social da Habitação, E. M., S. A.',
  504538314),
 'Fesnima - Animação de Olhão': ('FESNIMA, Empresa Pública de Animação de Olhão, E.M.',
  504667521),
 'Infralobo - Empresa de Infra\ue02dEstruturas': ('Infralobo - Empresa de Infra-Estruturas de Vale do Lobo, E. M.',
  504041193),
 'Trofáguas - Serviços Ambientais': ('Trofáguas - Serviços Ambientais, E.E.M.',
  506236838),
 'Gespaços - Gestão Equipamentos Municipais': ('Gespaços - Gestão de Equipamentos Municipais, E. M.',
  505317982),
 'Maiambiente': ('Maiambiente Empresa Municipal do Ambiente, E.M.', 505060868),
 'HABEVORA - Gestão habitacional': ('Habévora - Gestão Habitacional, E.E.M.',
  507013212),
 'EMAC - EM de Ambiente de Cascais': ('Emac - Empresa de Ambiente de Cascais, E.M., S.A.',
  507396081),
 'SMAS de Sintra': ('SMAS - Serviços Municipalizados de Sintra', 680000054),
 'Penafiel Verde - Entidade Empresarial Local': ('Penafiel Verde - Entidade Empresarial Local, E.E.M.',
  507700651),
 'Herdade da Contenda': ('Herdade da Contenda, E. M.', 509455484),
 'Interminho - Soc. Gestora de Parques Emp.': ('Interminho - Sociedade Gestora de Parques Empresariais, E.M.',
  504923242),
 'Prazilandia \ue02dTurismo e Ambiente': ('Prazilândia - Turismo e Ambiente, E. E. M.',
  506579794),
 'Nordeste Activo': ('Nordeste Activo - Empresa Municipal de Actividades Desportivas, Recreativas e Turísticas, Águas e Resíduos, E.E.M',
  512088357),
 'SMAS de Vila Franca Xira': ('SMAS -Município de Vila Franca de Xira',
  680021892),
 'TERAMB': ('Teramb - Empresa Municipal de Gestão e Valorização Ambiental da Ilha Terceira, EM',
  509620515),
 'Vimágua': ('Vimágua - Empresa de Água e Saneamento de Guimarães e Vizela, E.I.M. S.A.',
  505993082),
 'Porto Vivo, SRU': ('Porto Vivo, SRU - Sociedade de Reabilitação Urbana do Porto, E. M., S. A.',
  506866432),
 'MS Matosinhos Sport': ('MS - MATOSINHOS SPORT, EM', 506197174),
 'Loulé Concelho Global': ('Loulé Concelho Global, E. M., Unipessoal, S. A.',
  505493870),
 'Metropolitano Ligeiro de Mirandela': ('Metropolitano Ligeiro de Mirandela, S. A.',
  503518794),
 'APdSE - Águas Públicas da Serra da Estrela': ('Águas Públicas da Serra da Estrela, E. I. M., S. A.',
  515957631),
 'CMPEA - Águas do Porto': ('ÁGUAS DO PORTO, EM', 507718666),
 'Praia Ambiente': ('Praia Ambiente E.M.', 512097780),
 'Cascais Dinâmica': ('Dinâmica Secreta, Lda', 510152635),
 'GEMC - Gestão Equipamentos': ('Gestão de Equipamentos do Município de Chaves, E.M, S.A.',
  506695018),
 'SMAS - Alcobaça': ('SERVIÇOS MUNICIPALIZADOS ALCOBAÇA', 680014942),
 'SMAS de Viseu': ('Serviços Municipalizados de Viseu', 680020063),
 'SM de Viana Castelo': ('Serviços Municipalizados de Saneamento Básico de Viana do Castelo',
  680012907),
 'VRSA, Sociedade de Gestão Urbana': ('VRSA Sociedade de Gestão Urbana, E. M, S. A.',
  508160570),
 'WEMOB - EM, S.A': ('ECALMA - Empresa Municipal de Estacionamento e Circulação de Almada, E.M.',
  507001206),
 'ESPOSENDE 2000': ('Associação Banda dos Bombeiros Voluntários de Esposende',
  503879614),
 'DESMOR - Gestão Desportiva de Rio Maior': ('Desmor, E. M., S. A.',
  504748114),
 'SIMAS de Oeiras e Amadora': ('SMAS - OEIRAS (MUNICIPIO OEIRAS)', 680015019),
 'SIMAR de Loures e Odivelas': ('Serviços Municipalizados de Loures',
  680009671),
 'Inframoura - Empresa de Infra\ue02dEstruturas': ('Inframoura - Empresa de Infraestruturas de Vilamoura, E. M.',
  504915266),
 'Logica - Sociedade Gestora do Tecnológico': ('Lógica, SA', 508201306),
 'ÁGORA - Cultura e Desporto, EM, SA': ('CMPL - Porto Lazer - Empresa de Desporto e Lazer do Municipio do Porto, EM',
  507718640),
 'SMTUC - Transp. Urbanos de Coimbra': ('Serviços Municipalizados de Transportes Urbanos de Coimbra',
  680015965),
 'SMAS da Maia': ('Serviços Municipalizados de Águas e Saneamento Maia',
  680015124),
 'Giatul - Gest.. Infra\ue02dEstruturas Activ.Turísticas': ('GIATUL - Atividades Lúdicas Infraestruturas e Rodovias E. M. S. A.',
  506874915),
 'Gesloures - Gestão de Equipamentos Sociais': ('Gesloures, E.M.', 502814063),
 'Naturnorte - Gestão Eq. Colect. e Prest. Serv.': ('Naturnorte - Gestão de Equipamentos Coletivos e Prestação de Serviços, E. M., S. A.',
  511086040),
 'SM de Nazaré': ('SMAS - Nazaré ', 680017399),
 'Cascais Próxima': ('ESUC empresa de serviços urbanos de Cascais', 504853635),
 'InvestBraga - Agência p/ Dinamiz. Económica': ('PEB - Empresa Parque de Exposições de Braga, E.M.',
  504807706),
 'Penaparque 2 - Gestão e Promoção de Equip.': None,
 'Vallis Habita - Gestão Empreend. Habitacion.': ('Vallis Habita-Sociedade Municipal de Gestão de Empreendimentos Habitacionais de Valongo, EM',
  505265800),
 'SMAS de Leiria': ('Serviços Municipalizados de Água e Saneamento da Câmara Municipal de Leiria',
  680017550),
 'TUB - Transportes Urbanos': ('Transportes Urbanos de Braga - EM', 504807684),
 'CDN - Gestão e Promoção do Parque Emp.': None,
 'iParque - Parque Inov. Ciência, Tec. e Saúde': ('Coimbra Inovação Parque - Parque de Inovação em Ciência, Tecnologia, Saúde EM, S.A.',
  506787729),
 'EMEC - EM de Educação e Cultura': ('Empresa Municipal de Educação de Cultura de Barcelos',
  504635417),
 'Carnes de Vinhais \ue02dSoc. Abate Transf. Carnes': None,
 'Ambifaro\ue02dGestão de Equipamentos Municipais': ('Mercado Municipal de Faro, S.A.',
  504497782),
 'Matadouro Regional de Monção': None,
 'Águas de S. João': ('Águas de São João, E.M, S.A.', 508326567),
 'Marina da Vila - Indústrias Marinas e Recreio': None,
 'CMPH - Domus Social': ('CMPH - DomusSocial - Empresa de Habitação e manutenção do Município do Porto, EEM',
  505037700),
 'Habitar S. João - Habitação': ('Habitar S. João - Empresa Municipal de Habitação, E. M.',
  506546365),
 'Infraquinta - Empresa de Infra\ue02dEstruturas': ('Infraquinta - Empresa de Infraestruturas da Quinta do Lago, E. M.',
  503830704),
 'Tavira Verde - Ambiente': ('TAVIRAVERDE – Empresa Municipal de Ambiente, E. M.',
  507236335),
 'SMA de Abrantes': ('Serviços Municipalizados Abrantes', 680017542),
 'Matadouro Regional de Mafra': None,
 'SM de Castelo Branco': ('SMAS-Serviços Municipalizados A.S.Castelo Branco',
  680017640),
 'VISEUNOVO - SRU': ('Viseu Novo SRU - Sociedade de Reabilitação Urbana de Viseu SA',
  507406672),
 'SMAS de Ponta Delgada': ('Servicos Municipalizados Ponta Delgada',
  672001721),
 'SDVF - Soc. Desenv. Habit. Social de VFC': None,
 'CampoMaior XXI': ('Campomayor XXI - Empresa Municipal', 507745396),
 'Ribeira da Teja - Produção Energia Eléctrica': None,
 'ADC - Aguas da Covilhã': ('Adc, EM', 507611977),
 'SMAT de Portalegre': ('Serviços Municipalizados de Águas e Transportes',
  680031065),
 'Figueira Domus - Gestão de Habitação': None
 }